### ISSUE TITLE
User can update the status of all tasks, including other members

### ISSUE THREAD

**Issue by mattmatt0** [Robotechnic/AlmatiTodoList#4]
A logged user can  change EVERY task status, even if it isn't its own. For instance, I could change the status of the task `"test'`, created by user Robotechnic, to `à faire`.

**Expected behaviour**
The status shouldn't be able to be changed for tasks of other users.

**Comment by Robotechnic** [comment]
Now, you can put a task in private mode with a checkbox on creation menu and on the main page
